# Generated by Django 2.0.1 on 2018-01-16 16:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_title', models.CharField(max_length=200)),
                ('feature_desc', models.TextField()),
                ('target_date', models.DateField(verbose_name='date targetted')),
                ('create_date', models.DateTimeField(default=datetime.datetime(2018, 1, 16, 22, 12, 6, 923233))),
                ('client_priority', models.IntegerField(default=0)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_area', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='product_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.Product'),
        ),
    ]
